sudo: required
services:
  - docker

env:
  global:
    # REGISTRY_USER=
    # REGISTRY_PASS=
    - secret: "^TUDXG6j8zST%ZQ#h*GvSW&M3hjzDFqs"

before_script:
  - docker pull mrworf/pika2mqtt || true

script:
  - docker build --pull --cache-from mrworf/pika2mqtt --tag mrworf/pika2mqtt .

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push mrworf/pika2mqtt
  on:
    branch: master
