sudo: required

services:
- docker

env:
  global:
  - secure: Ec+Rb8bbb2XeUxOqrXQrj+MyqfrbzJ6RjRuKzmUVX1jDsX+JZd4JQmHLCbJRAQO2GN3WRX6JdQdmA2vhXbDPVU6IXTDuUNXPUm18awefYsG/f4CQ5wXC5j0SAdDZH0Gcrwzd4qySQI6kTJE1lPdeq13223g3gbTtxeRaDxL1IC957rUcqVcMreC45D7TaZjn+DSt+qaZOSZGiyjAzg4VH1DzNoZiVEUGWDRruljuPp7f2CNgrxf38Hfw2ufKs18X/34NxNA1Scgu7urWQZXffWNJfzpts3PWSoCdFkU5kN99YBOpChz3AF+mVwgivUujRGdYM69SayQLtxZtqUOVH2mALteZxt7U0M/jwWrOaQ5pyyIRiH4t6xzqHnLw4OdBTT1YKEZENKOJDMokHFY/vSesRtVRlr1natKyn5/YmFKCjCyk+fDQ1TQCHsmJ/lXkFDr4C4SV1ssahtF2Nd03XdZyme+KjOepSfnf4WhSsps+x9DCyyW15nDvhwyYKX8ztHtF/rNyDRdSy5dj9ZOpkq1LnVj+IDMG4PTNBh4G7O4DEs0u52OGr28UIjstxfrFgstDdysC5hihIfJOTnB78hSTED6zPDHlXLnYAjdvY/mDgIoEp2M8Q3sDQCAe1boSjM5zUxrFrqOAQj241xHCnDgTtlIq5MEkCWHcLQpROdk=

before_script:
- docker pull mrworf/pika2mqtt || true

script:
- docker build --pull --cache-from mrworf/pika2mqtt --tag mrworf/pika2mqtt .

before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push mrworf/pika2mqtt
  on:
    branch: master
