name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: pip install paho-mqtt
    - name: Run pika2mqtt.py
      run: |
        python3 -c "
        import subprocess
        ret = subprocess.run(['python3', 'pika2mqtt.py']).returncode
        if ret != 2:
            raise SystemExit(ret)
        "
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Main web app container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.USERNAME }}/pika2mqtt:latest
        file: ./Dockerfile